base_config: 'frameworks/pisr/configs/splainx3/base.ram.yml'


teacher_model:
  name: 'plainnet_teacher'
  params:
    scale: 3
    n_colors: 3
    m: 4
    k: 1
    encoder: lcscc
    n_feats: 64
    num_modules: 19


student_model:
  name: 'plainnet_student'
  params:
    scale: 3
    n_colors: 3
    n_feats: 64
    num_modules: 19
    initialize_from:
      - '../PISR/results/splainnetx3/plainnet_teacher/checkpoint/'
    modules_to_initialize:
      - - 'feature_extraction'
        - 'last_layer'
    vid_info:
      - 'feature_extraction:None'


train:
  batch_size: 16
  num_epochs: 1000
  teacher_dir: ''
  student_dir: ''


eval:
  batch_size: 1


scheduler:
  name: 'cosine'
  params:
    T_max: 1000
    eta_min: 0.00001


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'vid_loss'
  params:
    reduction: 'mean'
    lambda1: 1
    lambda2: 0.000001
    pdf: laplace


visualizer:
  name: 'step2'


gpu: 6


